In [27]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import DecisionTreeRegressor
from sklearn.preprocessing import LabelEncoder
from sklearn.cross_validation import cross_val_score, StratifiedKFold, train_test_split, KFold
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier, BaggingClassifier, RandomForestRegressor
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.grid_search import GridSearchCV
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression

In [28]:
import pandas as pd
df = pd.read_csv('df4.csv', index_col=0)

In [29]:
df.shape

(654313, 96)

In [30]:
df.columns

Index([u'TOR_LENGTH', u'TOR_WIDTH', u'is_Drought', u'is_Flood',
       u'is_Winter Storm', u'is_OTHER', u'is_High Wind', u'is_ThunderStorm',
       u'is_Wildfire', u'is_Rip Current', u'is_Tropical Storm', u'is_Tornado',
       u'is_Hurricane', u'is_Tsunami', u'is_Landslide', u'TD', u'TI',
       u'is_EF0', u'is_EF1', u'is_EF2', u'is_EF3', u'is_EF4', u'is_EF5',
       u'is_F0', u'is_F1', u'is_F2', u'is_F3', u'is_F4', u'is_ALABAMA',
       u'is_ALASKA', u'is_AMERICAN SAMOA', u'is_ARIZONA', u'is_ARKANSAS',
       u'is_ATLANTIC NORTH', u'is_ATLANTIC SOUTH', u'is_CALIFORNIA',
       u'is_COLORADO', u'is_CONNECTICUT', u'is_DELAWARE',
       u'is_DISTRICT OF COLUMBIA', u'is_E PACIFIC', u'is_FLORIDA',
       u'is_GEORGIA', u'is_GUAM', u'is_GULF OF ALASKA', u'is_GULF OF MEXICO',
       u'is_HAWAII', u'is_HAWAII WATERS', u'is_IDAHO', u'is_ILLINOIS',
       u'is_INDIANA', u'is_IOWA', u'is_KANSAS', u'is_KENTUCKY',
       u'is_LAKE ERIE', u'is_LAKE HURON', u'is_LAKE MICHIGAN',
       u'is_LAKE ONTARIO', u'is_LAKE ST CLAIR', u'is_LAKE SUPERIOR',
       u'is_LOUISIANA', u'is_MAINE', u'is_MARYLAND', u'is_MASSACHUSETTS',
       u'is_MICHIGAN', u'is_MINNESOTA', u'is_MISSISSIPPI', u'is_MISSOURI',
       u'is_MONTANA', u'is_NEBRASKA', u'is_NEVADA', u'is_NEW HAMPSHIRE',
       u'is_NEW JERSEY', u'is_NEW MEXICO', u'is_NEW YORK',
       u'is_NORTH CAROLINA', u'is_NORTH DAKOTA', u'is_OHIO', u'is_OKLAHOMA',
       u'is_OREGON', u'is_PENNSYLVANIA', u'is_PUERTO RICO', u'is_RHODE ISLAND',
       u'is_SOUTH CAROLINA', u'is_SOUTH DAKOTA', u'is_ST LAWRENCE R',
       u'is_TENNESSEE', u'is_TEXAS', u'is_UTAH', u'is_VERMONT',
       u'is_VIRGIN ISLANDS', u'is_VIRGINIA', u'is_WASHINGTON',
       u'is_WEST VIRGINIA', u'is_WISCONSIN', u'is_WYOMING'],
      dtype='object')

In [35]:
graph= df.describe()

In [36]:
graph

,TOR_LENGTH,TOR_WIDTH,is_Drought,is_Flood,is_Winter Storm,is_OTHER,is_High Wind,is_ThunderStorm,is_Wildfire,is_Rip Current,...,is_TENNESSEE,is_TEXAS,is_UTAH,is_VERMONT,is_VIRGIN ISLANDS,is_VIRGINIA,is_WASHINGTON,is_WEST VIRGINIA,is_WISCONSIN,is_WYOMING
count,654313.000000,654313.000000,654313.000000,654313.000000,654313.000000,654313.000000,654313.000000,654313.000000,654313.000000,654313.000000,...,654313.000000,654313.000000,654313.000000,654313.000000,654313.000000,654313.000000,654313.000000,654313.000000,654313.000000,654313.000000
mean,0.074317,3.637183,0.068638,0.106464,0.411760,0.009868,0.044421,0.309668,0.005673,0.000908,...,0.023927,0.069227,0.006355,0.006674,0.000271,0.028853,0.005072,0.011657,0.023666,0.010217
std,1.221615,46.757279,0.252838,0.308431,0.492153,0.098848,0.206028,0.462357,0.075106,0.030116,...,0.152823,0.253840,0.079463,0.081423,0.016445,0.167394,0.071041,0.107334,0.152007,0.100561
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,400.000000,4576.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [37]:
df.TD.describe()

count    654313.000000
mean          0.006848
std           0.082471
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: TD, dtype: float64

In [38]:
df.TI.describe()

count    654313.000000
mean          0.010668
std           0.102732
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: TI, dtype: float64

In [33]:
df1.groupby('EVENT_TYPE').COMBINED_DAMAGE.agg(['count','min', 'max', 'mean', 'sum']).sort_values('sum', axis=0, ascending=False).reset_index().head(10)

AttributeError: 'Series' object has no attribute 'agg'

In [5]:
for column in df.columns:
    print df[column].describe()

count    654313.000000
mean          0.074317
std           1.221615
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max         400.000000
Name: TOR_LENGTH, dtype: float64
count    654313.000000
mean          3.637183
std          46.757279
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max        4576.000000
Name: TOR_WIDTH, dtype: float64
count    654313.000000
mean          0.068638
std           0.252838
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_Drought, dtype: float64
count    654313.000000
mean          0.106464
std           0.308431
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_Flood, dtype: float64
count    654313.000000
mean          0.411760
std           0.492153
min           0.000000
25%           0.000000
50%           0.000000
75%           1.000000
max           1.000000
Name: is_Winter Storm, dtype: float64
count    654313.000000
mean          0.009868
std           0.098848
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_OTHER, dtype: float64
count    654313.000000
mean          0.044421
std           0.206028
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_High Wind, dtype: float64
count    654313.000000
mean          0.309668
std           0.462357
min           0.000000
25%           0.000000
50%           0.000000
75%           1.000000
max           1.000000
Name: is_ThunderStorm, dtype: float64
count    654313.000000
mean          0.005673
std           0.075106
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_Wildfire, dtype: float64
count    654313.000000
mean          0.000908
std           0.030116
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_Rip Current, dtype: float64
count    654313.000000
mean          0.008875
std           0.093788
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_Tropical Storm, dtype: float64
count    654313.000000
mean          0.030863
std           0.172946
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_Tornado, dtype: float64
count    654313.000000
mean          0.002263
std           0.047522
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_Hurricane, dtype: float64
count    654313.000000
mean          0.000044
std           0.006657
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_Tsunami, dtype: float64
count    654313.000000
mean          0.000553
std           0.023515
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_Landslide, dtype: float64
count    654313.000000
mean          0.006848
std           0.082471
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: TD, dtype: float64
count    654313.000000
mean          0.010668
std           0.102732
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: TI, dtype: float64
count    654313.000000
mean          0.008178
std           0.090062
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_EF0, dtype: float64
count    654313.000000
mean          0.004771
std           0.068911
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_EF1, dtype: float64
count    654313.000000
mean          0.001571
std           0.039606
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_EF2, dtype: float64
count    654313.000000
mean          0.000501
std           0.022384
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_EF3, dtype: float64
count    654313.000000
mean          0.000124
std           0.011126
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_EF4, dtype: float64
count    654313.000000
mean          0.000021
std           0.004626
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_EF5, dtype: float64
count    654313.000000
mean          0.005724
std           0.075437
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_F0, dtype: float64
count    654313.000000
mean          0.002458
std           0.049513
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_F1, dtype: float64
count    654313.000000
mean          0.000663
std           0.025746
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_F2, dtype: float64
count    654313.000000
mean          0.000197
std           0.014040
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_F3, dtype: float64
count    654313.000000
mean          0.000037
std           0.006056
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_F4, dtype: float64
count    654313.000000
mean          0.023675
std           0.152035
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_ALABAMA, dtype: float64
count    654313.000000
mean          0.005290
std           0.072537
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_ALASKA, dtype: float64
count    654313.000000
mean          0.000267
std           0.016352
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_AMERICAN SAMOA, dtype: float64
count    654313.000000
mean          0.006936
std           0.082991
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_ARIZONA, dtype: float64
count    654313.000000
mean          0.025644
std           0.158070
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_ARKANSAS, dtype: float64
count    654313.000000
mean          0.006718
std           0.081691
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_ATLANTIC NORTH, dtype: float64
count    654313.000000
mean          0.003694
std           0.060666
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_ATLANTIC SOUTH, dtype: float64
count    654313.000000
mean          0.014461
std           0.119381
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_CALIFORNIA, dtype: float64
count    654313.000000
mean          0.025427
std           0.157417
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_COLORADO, dtype: float64
count    654313.000000
mean          0.003650
std           0.060302
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_CONNECTICUT, dtype: float64
count    654313.000000
mean          0.002780
std           0.052653
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_DELAWARE, dtype: float64
count    654313.000000
mean          0.000436
std           0.020866
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_DISTRICT OF COLUMBIA, dtype: float64
count    654313.000000
mean          0.000215
std           0.014678
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_E PACIFIC, dtype: float64
count    654313.000000
mean          0.017171
std           0.129907
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_FLORIDA, dtype: float64
count    654313.000000
mean          0.028870
std           0.167441
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_GEORGIA, dtype: float64
count    654313.000000
mean          0.000188
std           0.013709
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_GUAM, dtype: float64
count    654313.000000
mean          0.000073
std           0.008565
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_GULF OF ALASKA, dtype: float64
count    654313.000000
mean          0.009038
std           0.094640
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_GULF OF MEXICO, dtype: float64
count    654313.000000
mean          0.008702
std           0.092879
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_HAWAII, dtype: float64
count    654313.000000
mean          0.000041
std           0.006424
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_HAWAII WATERS, dtype: float64
count    654313.000000
mean          0.004846
std           0.069447
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_IDAHO, dtype: float64
count    654313.000000
mean          0.035495
std           0.185028
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_ILLINOIS, dtype: float64
count    654313.000000
mean          0.023180
std           0.150475
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_INDIANA, dtype: float64
count    654313.000000
mean          0.036337
std           0.187128
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_IOWA, dtype: float64
count    654313.000000
mean          0.049264
std           0.216419
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_KANSAS, dtype: float64
count    654313.000000
mean          0.031069
std           0.173505
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_KENTUCKY, dtype: float64
count    654313.000000
mean          0.002091
std           0.045677
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_LAKE ERIE, dtype: float64
count    654313.000000
mean          0.000963
std           0.031015
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_LAKE HURON, dtype: float64
count    654313.000000
mean          0.002369
std           0.048614
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_LAKE MICHIGAN, dtype: float64
count    654313.000000
mean          0.000150
std           0.012237
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_LAKE ONTARIO, dtype: float64
count    654313.000000
mean          0.000436
std           0.020866
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_LAKE ST CLAIR, dtype: float64
count    654313.000000
mean          0.000700
std           0.026448
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_LAKE SUPERIOR, dtype: float64
count    654313.000000
mean          0.012123
std           0.109434
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_LOUISIANA, dtype: float64
count    654313.000000
mean          0.008386
std           0.091190
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_MAINE, dtype: float64
count    654313.000000
mean          0.011846
std           0.108193
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_MARYLAND, dtype: float64
count    654313.000000
mean          0.007078
std           0.083831
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_MASSACHUSETTS, dtype: float64
count    654313.000000
mean          0.019330
std           0.137683
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_MICHIGAN, dtype: float64
count    654313.000000
mean          0.027267
std           0.162860
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_MINNESOTA, dtype: float64
count    654313.000000
mean          0.020678
std           0.142305
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_MISSISSIPPI, dtype: float64
count    654313.000000
mean          0.039613
std           0.195047
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_MISSOURI, dtype: float64
count    654313.000000
mean          0.018244
std           0.133831
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_MONTANA, dtype: float64
count    654313.000000
mean          0.031153
std           0.173732
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_NEBRASKA, dtype: float64
count    654313.000000
mean          0.003384
std           0.058071
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_NEVADA, dtype: float64
count    654313.000000
mean          0.004321
std           0.065589
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_NEW HAMPSHIRE, dtype: float64
count    654313.000000
mean          0.014974
std           0.121451
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_NEW JERSEY, dtype: float64
count    654313.000000
mean          0.011310
std           0.105743
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_NEW MEXICO, dtype: float64
count    654313.000000
mean          0.026701
std           0.161209
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_NEW YORK, dtype: float64
count    654313.000000
mean          0.031028
std           0.173393
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_NORTH CAROLINA, dtype: float64
count    654313.000000
mean          0.017074
std           0.129549
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_NORTH DAKOTA, dtype: float64
count    654313.000000
mean          0.024332
std           0.154079
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_OHIO, dtype: float64
count    654313.000000
mean          0.033281
std           0.179369
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_OKLAHOMA, dtype: float64
count    654313.000000
mean          0.007053
std           0.083687
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_OREGON, dtype: float64
count    654313.000000
mean          0.025153
std           0.156590
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_PENNSYLVANIA, dtype: float64
count    654313.000000
mean          0.003760
std           0.061201
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_PUERTO RICO, dtype: float64
count    654313.000000
mean          0.000989
std           0.031430
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_RHODE ISLAND, dtype: float64
count    654313.000000
mean          0.018268
std           0.133919
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_SOUTH CAROLINA, dtype: float64
count    654313.000000
mean          0.026544
std           0.160746
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_SOUTH DAKOTA, dtype: float64
count    654313.000000
mean          0.000015
std           0.003909
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_ST LAWRENCE R, dtype: float64
count    654313.000000
mean          0.023927
std           0.152823
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_TENNESSEE, dtype: float64
count    654313.000000
mean          0.069227
std           0.253840
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_TEXAS, dtype: float64
count    654313.000000
mean          0.006355
std           0.079463
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_UTAH, dtype: float64
count    654313.000000
mean          0.006674
std           0.081423
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_VERMONT, dtype: float64
count    654313.000000
mean          0.000271
std           0.016445
min           0.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           1.000000
Name: is_VIRGIN ISLANDS, dtype: float64
count    654313.000000
mean          0.028853
std           0.167394
min           0.000000
25%           0.000000

In [26]:
df.mean.sort_values('sum', axis=0, ascending=False).reset_index().head(10)

AttributeError: 'function' object has no attribute 'sort_values'

In [13]:
df = df.sample(frac=0.5)
df.reset_index(drop=True, inplace=True)

In [14]:
df.shape

(20448, 96)

In [15]:
le = LabelEncoder()
y = le.fit_transform(df['TD'])
X = pd.get_dummies(df.drop('TD', axis=1))

In [16]:
y.shape

(20448,)

In [17]:
X.shape

(20448, 95)

In [18]:
def get_cv(target):
    return StratifiedKFold(target, n_folds=3, shuffle=True, random_state=41)

In [19]:

def score(model, data, target):
    model.fit(data, target)
    return model.score(data, target)

In [20]:

def grid_search(model, params, cv):
    return GridSearchCV(estimator=model, 
                    param_grid=params,
                    cv=cv
                   )

In [21]:

def evaluate_model(model, data, target, params=None):
    x_train, x_test, y_train, y_test=train_test_split(data, target, stratify=target)
#     print score(model, x_train, y_train), "\n"
    cv=get_cv(y_train)
    if params:
        grid=grid_search(model, params, cv)
    
        grid.fit(x_train, y_train)
        model = grid.best_estimator_
        print "Best Model after Grid Search:\n", model
        
    else:
        model.fit(x_train, y_train)
        
    s=cross_val_score(model, x_train, y_train, cv=cv, n_jobs=-1)
    print "Mean score of the model is: {}".format(s.mean())
    predictions = model.predict(x_test)
    
    print "Confusion Matrix:\n",confusion_matrix(y_test, predictions), "\n"
    print "Classification Report:\n", classification_report(y_test, predictions)
    return model

In [138]:
# RandomForestClassifier()
params = {
    'n_estimators': [5, 10, 25],
    'max_depth': [None,1, 2, 8, 16],
    'min_samples_split': [2, 10, 25],
}
rfc=evaluate_model(RandomForestClassifier(class_weight='balanced', n_jobs=-1), X, y,  params)

Best Model after Grid Search:
RandomForestClassifier(bootstrap=True, class_weight='balanced',
            criterion='gini', max_depth=2, max_features='auto',
            max_leaf_nodes=None, min_samples_leaf=1, min_samples_split=25,
            min_weight_fraction_leaf=0.0, n_estimators=25, n_jobs=-1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)
Mean score of the model is: 0.9119319003
Confusion Matrix:
[[73562  7674]
 [  284   270]]

Classification Report:
             precision    recall  f1-score   support

          0       1.00      0.91      0.95     81236
          1       0.03      0.49      0.06       554

avg / total       0.99      0.90      0.94     81790

In [139]:

params = {
    'C': [.2,.5,.75,1.0],
    'penalty':['l1','l2'],
}

lr=evaluate_model(LogisticRegression(class_weight='balanced', n_jobs=1),  X, y, params)

# Going to want to print out the coef_
# Did they die? Were there any costs? Binary

Best Model after Grid Search:
LogisticRegression(C=1.0, class_weight='balanced', dual=False,
          fit_intercept=True, intercept_scaling=1, max_iter=100,
          multi_class='ovr', n_jobs=1, penalty='l1', random_state=None,
          solver='liblinear', tol=0.0001, verbose=0, warm_start=False)
Mean score of the model is: 0.802720056235
Confusion Matrix:
[[65023 16213]
 [  173   381]]

Classification Report:
             precision    recall  f1-score   support

          0       1.00      0.80      0.89     81236
          1       0.02      0.69      0.04       554

avg / total       0.99      0.80      0.88     81790

In [24]:
knn=KNeighborsClassifier()
params={}
knn=evaluate_model(knn, X, y, params)

Mean score of the model is: 0.993675038388
Confusion Matrix:
[[5080    0]
 [  32    0]]

Classification Report:
             precision    recall  f1-score   support

          0       0.99      1.00      1.00      5080
          1       0.00      0.00      0.00        32

avg / total       0.99      0.99      0.99      5112

/Users/ugp/anaconda2/lib/python2.7/site-packages/sklearn/metrics/classification.py:1074: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)

In [154]:
# DecisionTreeClassifier()
params = {
    'max_depth': [None,1, 8, 16],
    'min_samples_split': [2, 10, 25, 50, 100],
}
dtc=evaluate_model(DecisionTreeClassifier(), X, y, params)

Best Model after Grid Search:
DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=8,
            max_features=None, max_leaf_nodes=None, min_samples_leaf=1,
            min_samples_split=25, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')
Mean score of the model is: 0.993548438836
Confusion Matrix:
[[81215    16]
 [  487    72]]

Classification Report:
             precision    recall  f1-score   support

          0       0.99      1.00      1.00     81231
          1       0.82      0.13      0.22       559

avg / total       0.99      0.99      0.99     81790

In [155]:
# ExtraTreesClassifier
params = {
    'n_estimators': [10, 20, 50],
    'max_depth': [None,1, 2, 3, 4, 5],
    'min_samples_split': [2, 10, 25, 50],
}
etc=evaluate_model(ExtraTreesClassifier(class_weight='balanced', n_jobs=-1), X, y, params)

Best Model after Grid Search:
ExtraTreesClassifier(bootstrap=False, class_weight='balanced',
           criterion='gini', max_depth=1, max_features='auto',
           max_leaf_nodes=None, min_samples_leaf=1, min_samples_split=25,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=-1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)
Mean score of the model is: 0.710311539192
Confusion Matrix:
[[80386   845]
 [  378   181]]

Classification Report:
             precision    recall  f1-score   support

          0       1.00      0.99      0.99     81231
          1       0.18      0.32      0.23       559

avg / total       0.99      0.99      0.99     81790

In [156]:
# DecisionTreeClassifier()
params = {

}
tdtc=evaluate_model(BaggingClassifier(DecisionTreeClassifier()), X, y, params)

Mean score of the model is: 0.993413947968
Confusion Matrix:
[[81189    42]
 [  488    71]]

Classification Report:
             precision    recall  f1-score   support

          0       0.99      1.00      1.00     81231
          1       0.63      0.13      0.21       559

avg / total       0.99      0.99      0.99     81790

In [157]:
params = {

}
lgbag=evaluate_model(BaggingClassifier(LogisticRegression()), X, y, params)

Mean score of the model is: 0.993471003761
Confusion Matrix:
[[81205    26]
 [  518    41]]

Classification Report:
             precision    recall  f1-score   support

          0       0.99      1.00      1.00     81231
          1       0.61      0.07      0.13       559

avg / total       0.99      0.99      0.99     81790

In [25]:
params = {
    'verbose': [10]}
knnbag=evaluate_model(BaggingClassifier(KNeighborsClassifier()), X, y, params)

building estimator 1 of 10
building estimator 2 of 10
building estimator 3 of 10
building estimator 4 of 10
building estimator 5 of 10
building estimator 6 of 10
building estimator 7 of 10
building estimator 8 of 10
building estimator 9 of 10
building estimator 10 of 10

[Parallel(n_jobs=1)]: Done   1 tasks       | elapsed:    2.1s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    2.1s finished
[Parallel(n_jobs=1)]: Done   1 tasks       | elapsed:   34.9s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:   34.9s finished

building estimator 1 of 10
building estimator 2 of 10
building estimator 3 of 10
building estimator 4 of 10
building estimator 5 of 10
building estimator 6 of 10
building estimator 7 of 10
building estimator 8 of 10
building estimator 9 of 10
building estimator 10 of 10

[Parallel(n_jobs=1)]: Done   1 tasks       | elapsed:    2.1s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    2.1s finished
[Parallel(n_jobs=1)]: Done   1 tasks       | elapsed:   34.8s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:   34.8s finished

building estimator 1 of 10
building estimator 2 of 10
building estimator 3 of 10
building estimator 4 of 10
building estimator 5 of 10
building estimator 6 of 10
building estimator 7 of 10
building estimator 8 of 10
building estimator 9 of 10
building estimator 10 of 10

[Parallel(n_jobs=1)]: Done   1 tasks       | elapsed:    2.1s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    2.1s finished
[Parallel(n_jobs=1)]: Done   1 tasks       | elapsed:   36.7s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:   36.7s finished

building estimator 1 of 10
building estimator 2 of 10
building estimator 3 of 10
building estimator 4 of 10
building estimator 5 of 10
building estimator 6 of 10
building estimator 7 of 10
building estimator 8 of 10
building estimator 9 of 10
building estimator 10 of 10
Best Model after Grid Search:
BaggingClassifier(base_estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform'),
         bootstrap=True, bootstrap_features=False, max_features=1.0,
         max_samples=1.0, n_estimators=10, n_jobs=1, oob_score=False,
         random_state=None, verbose=10, warm_start=False)

[Parallel(n_jobs=1)]: Done   1 tasks       | elapsed:    4.8s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    4.8s finished

building estimator 1 of 10
building estimator 1 of 10
building estimator 1 of 10
building estimator 2 of 10
building estimator 2 of 10
building estimator 2 of 10
building estimator 3 of 10
building estimator 3 of 10
building estimator 3 of 10
building estimator 4 of 10
building estimator 4 of 10
building estimator 4 of 10
building estimator 5 of 10
building estimator 5 of 10
building estimator 5 of 10
building estimator 6 of 10
building estimator 6 of 10
building estimator 6 of 10
building estimator 7 of 10
building estimator 7 of 10
building estimator 7 of 10
building estimator 8 of 10
building estimator 8 of 10
building estimator 8 of 10
building estimator 9 of 10
building estimator 9 of 10
building estimator 9 of 10
building estimator 10 of 10
building estimator 10 of 10
building estimator 10 of 10

[Parallel(n_jobs=1)]: Done   1 tasks       | elapsed:    2.4s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    2.4s finished
[Parallel(n_jobs=1)]: Done   1 tasks       | elapsed:    2.4s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    2.4s finished
[Parallel(n_jobs=1)]: Done   1 tasks       | elapsed:    2.4s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    2.4s finished
[Parallel(n_jobs=1)]: Done   1 tasks       | elapsed:   45.4s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:   45.4s finished
[Parallel(n_jobs=1)]: Done   1 tasks       | elapsed:   45.5s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:   45.5s finished
[Parallel(n_jobs=1)]: Done   1 tasks       | elapsed:   46.2s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:   46.2s finished

Mean score of the model is: 0.993544600774
Confusion Matrix:
[[5080    0]
 [  32    0]]

Classification Report:
             precision    recall  f1-score   support

          0       0.99      1.00      1.00      5080
          1       0.00      0.00      0.00        32

avg / total       0.99      0.99      0.99      5112

[Parallel(n_jobs=1)]: Done   1 tasks       | elapsed:   53.3s
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:   53.3s finished