### JayMichChi Part 2 Capstone
### Goal: Jays summary notebook outlining your project's goals, methods, models, and EDA.

This will be an overview of my approach with a well-articulated summary that includes your problem statement, outlines your proposed methods and models, defines any risks & assumptions, and includes any revisions from your initial goals & criteria, as needed.

In addition, I will explain how I intend to store my data. 

You'll want to describe and create a data dictionary for your dataset(s), and perform your initial exploratory data analysis.

### My Initial Goals
My capstone takes data from the National Centers for Environmental Information, particularly information from 2003 to 2013, and will look at unusual storm occurrences and unusual weather phenomena, and mores specifically, information on storm paths, deaths, injuries, and property damage. 

### My hypothesis is:
Can we reasonably predict the amount of annual deaths due to certain types of storm occurances based on past data?

#### Information about the data:
National Centers for Environmental Information (NCEI) is responsible for hosting and providing access to one of the most significant archives on Earth, with comprehensive oceanic, atmospheric, and geophysical data. From the depths of the ocean to the surface of the sun and from million-year-old sediment records to near real-time satellite images, NCEI is the Nation’s leading authority for environmental information.  It is from this source that I will primarily ingest data on the following: https://www.ncdc.noaa.gov/stormevents/

### Storm Events Database
The Storm Events Database contains a chronological listing, by states, of storm occurrences and unusual weather phenomena. Reports contain information on storm paths, deaths, injuries, and property damage.s

The Storm Events Database currently contains data from January 1950 to August 2016, as entered by NOAA's National Weather Service (NWS). Due to changes in the data collection and processing procedures over time, there are unique periods of record available depending on the event type. I have chosen to look at the data from 1996 to 2013.

### Data base
I was able to find the data on the following NCDC website FTP server. 
ftp://ftp.ncdc.noaa.gov/pub/data/swdi/stormevents/csvfiles/legacy/

    Index of /pub/data/swdi/stormevents/csvfiles/legacy/
    Name	Size	Date Modified
    ugc_areas.csv	902 kB	2/18/14, 12:00:00 AM
    stormdata_2013.csv	53.1 MB	1/31/14, 12:00:00 AM
    stormdata_2012.csv	64.3 MB	1/31/14, 12:00:00 AM
    stormdata_2011.csv	82.3 MB	1/31/14, 12:00:00 AM
    stormdata_2010.csv	62.5 MB	1/31/14, 12:00:00 AM
    Stormdata_2009.csv	49.9 MB	9/19/13, 12:00:00 AM
    Stormdata_2008.csv	60.6 MB	9/19/13, 12:00:00 AM
    Stormdata_2007.csv	49.7 MB	9/19/13, 12:00:00 AM
    Stormdata_2006.csv	26.0 MB	9/19/13, 12:00:00 AM
    Stormdata_2005.csv	34.9 MB	9/19/13, 12:00:00 AM
    Stormdata_2004.csv	33.1 MB	9/19/13, 12:00:00 AM
    Stormdata_2003.csv	32.1 MB	9/19/13, 12:00:00 AM
    Stormdata_2002.csv	32.0 MB	9/19/13, 12:00:00 AM
    Stormdata_2001.csv	30.6 MB	9/19/13, 12:00:00 AM
    Stormdata_2000.csv	35.7 MB	9/19/13, 12:00:00 AM
    Stormdata_1999.csv	34.9 MB	9/19/13, 12:00:00 AM
    Stormdata_1998.csv	37.8 MB	9/19/13, 12:00:00 AM
    Stormdata_1997.csv	25.0 MB	9/19/13, 12:00:00 AM
    Stormdata_1996.csv	22.9 MB	9/19/13, 12:00:00 AM
    [parent directory]		


I have successfully downloaded all 18 CSV files. My work will show that i merged the data via pandas concant processes.

### Requirements

Your work must:

- Articulate “Specific aim”

My goal DONE

- Outline proposed methods and models

Proposed methods are gathering the data, cleaning the date, fitting it to a few modles, TTS, run/score/graph

Logistic Regression /  Linear Regression

- Define risks & assumptions

Annual events: need to be carefully 
confounding factors effect costings, fatalities that may not be completely repesented in the weather realated incident. National Guard, federal funding

- Revise initial goals & success criteria, as needed

- Create local database
DONE on DBX
- Describe data cleaning/munging techniques

No Probe

- Create a data dictionary

summary explanation of each of the features

- Perform & summarize EDA

exploratory data analysis summary

- ***Bonus:***
 - Explain how you intend to evaluate your results. What tuning metric and evaluation approaches do you intend to use?
 
 clean fit run models, look at the results... 
 linear: error RSM differential 
 logistic ;  classification accuracy score, confusion matrix
coorelation number 
 - Identify 1-2 additional datasets that may help you triangulate your findings. How might these relate to your data?
aircraft incident, NTSB site
Crop damage, crop price website

- Create a blog post of at least 500 words (and 1-2 graphics!) that describes your assumptions and processes for EDA. Link to it in your Jupyter notebook.


---

### Necessary Deliverables / Submission

 - Materials must be submitted in a clearly labeled Jupyter notebook, including:
  - Markdown writeups, code, and visualizations
 - Create your own repository under your user name, submit a link to that repository with your findings.

---

### Suggested Ways to Get Started

- Don’t hesitate to write throwaway code to solve short term problems
- Read the docs for whatever technologies you use. Most of the time, there is a tutorial that you can follow, but not always, and learning to read documentation is crucial to your success!
- Write pseudocode before you write actual code. Thinking through the logic of something helps.  
- Document **everything**.


### Useful Resources

- [Exploratory Data Analysis](http://insightdatascience.com/blog/eda-and-graphics-eli-bressert.html)
- [Best practices for data documentation](https://www.dataone.org/all-best-practices)

In [29]:
#here is my scroll. it works, but the database url_base changes in y2010, 
# so i will re-run this with the updated base_url
import pandas as pd
import time
url_list = ['ftp://ftp.ncdc.noaa.gov/pub/data/swdi/stormevents/csvfiles/legacy/Stormdata_2003.csv']
web_count= 2003
for pages in range(1,7):
    web_count= 1 + web_count
    count_update=str(web_count)
    base_url = 'ftp://ftp.ncdc.noaa.gov/pub/data/swdi/stormevents/csvfiles/legacy/Stormdata_' + count_update + '.csv'
    url_list.append(base_url)
url_list
# This works wonderfully!

['ftp://ftp.ncdc.noaa.gov/pub/data/swdi/stormevents/csvfiles/legacy/Stormdata_2003.csv',
 'ftp://ftp.ncdc.noaa.gov/pub/data/swdi/stormevents/csvfiles/legacy/Stormdata_2004.csv',
 'ftp://ftp.ncdc.noaa.gov/pub/data/swdi/stormevents/csvfiles/legacy/Stormdata_2005.csv',
 'ftp://ftp.ncdc.noaa.gov/pub/data/swdi/stormevents/csvfiles/legacy/Stormdata_2006.csv',
 'ftp://ftp.ncdc.noaa.gov/pub/data/swdi/stormevents/csvfiles/legacy/Stormdata_2007.csv',
 'ftp://ftp.ncdc.noaa.gov/pub/data/swdi/stormevents/csvfiles/legacy/Stormdata_2008.csv',
 'ftp://ftp.ncdc.noaa.gov/pub/data/swdi/stormevents/csvfiles/legacy/Stormdata_2009.csv']

In [30]:
# This is my one time function that will load, append
# for url in url_list:
data1 = []
for url in url_list:
    page = pd.read_csv((url)) 
    data1.append(page)
    time.sleep(3.0)

In [31]:
data1_all = pd.concat(data1, axis=0)

In [32]:
print data1_all.shape

(396035, 58)

In [2]:
#as above
# so i will re-run this with the updated base_url

import time
url_list_2 = ['ftp://ftp.ncdc.noaa.gov/pub/data/swdi/stormevents/csvfiles/legacy/stormdata_2010.csv']
web_count= 2010
for pages in range(1,4):
    web_count= 1 + web_count
    count_update=str(web_count)
    base_url_2 = 'ftp://ftp.ncdc.noaa.gov/pub/data/swdi/stormevents/csvfiles/legacy/stormdata_' + count_update + '.csv'
    url_list_2.append(base_url_2)
url_list_2
# This works wonderfully!

['ftp://ftp.ncdc.noaa.gov/pub/data/swdi/stormevents/csvfiles/legacy/stormdata_2010.csv',
 'ftp://ftp.ncdc.noaa.gov/pub/data/swdi/stormevents/csvfiles/legacy/stormdata_2011.csv',
 'ftp://ftp.ncdc.noaa.gov/pub/data/swdi/stormevents/csvfiles/legacy/stormdata_2012.csv',
 'ftp://ftp.ncdc.noaa.gov/pub/data/swdi/stormevents/csvfiles/legacy/stormdata_2013.csv']

In [4]:
# This is my one time function that will load, append
# for url in url_list:
import pandas as pd
data2 = []
for url in url_list_2:
    page = pd.read_csv((url)) 
    data2.append(page)
    time.sleep(30.0)

In [5]:
data2_all=pd.concat(data2, axis=0)

In [33]:
data2_all.shape

(258278, 58)

In [34]:
df_all = pd.concat([data1_all, data2_all], axis=0)

In [35]:
df_all.shape

(654313, 58)

In [36]:
print df_all.columns

Index([u'BEGIN_YEARMONTH', u'BEGIN_DAY', u'BEGIN_TIME', u'END_YEARMONTH',
       u'END_DAY', u'END_TIME', u'EPISODE_ID', u'EVENT_ID', u'STATE',
       u'STATE_FIPS', u'YEAR', u'MONTH_NAME', u'EVENT_TYPE', u'CZ_TYPE',
       u'CZ_FIPS', u'CZ_NAME', u'WFO', u'BEGIN_DATE_TIME', u'CZ_TIMEZONE',
       u'END_DATE_TIME', u'INJURIES_DIRECT', u'INJURIES_INDIRECT',
       u'DEATHS_DIRECT', u'DEATHS_INDIRECT', u'DAMAGE_PROPERTY',
       u'DAMAGE_CROPS', u'SOURCE', u'MAGNITUDE', u'MAGNITUDE_TYPE',
       u'FLOOD_CAUSE', u'CATEGORY', u'TOR_F_SCALE', u'TOR_LENGTH',
       u'TOR_WIDTH', u'TOR_OTHER_WFO', u'TOR_OTHER_CZ_STATE',
       u'TOR_OTHER_CZ_FIPS', u'TOR_OTHER_CZ_NAME', u'BEGIN_RANGE',
       u'BEGIN_AZIMUTH', u'BEGIN_LOCATION', u'END_RANGE', u'END_AZIMUTH',
       u'END_LOCATION', u'BEGIN_LAT', u'BEGIN_LON', u'END_LAT', u'END_LON',
       u'EPISODE_NARRATIVE', u'EVENT_NARRATIVE', u'LAST_MOD_DATE',
       u'LAST_MOD_TIME', u'LAST_CERT_DATE', u'LAST_CERT_TIME', u'LAST_MOD',
       u'LAST_CERT', u'ADDCORR_FLG', u'ADDCORR_DATE'],
      dtype='object')

In [37]:
#convert dataframe to csv

df_all.to_csv('jm_cap.csv')
#This worked!  Thank God this was successful on Tuesday school!
# 10 years worth of data (654313, 58)

In [38]:
import pandas as pd
df1 = pd.read_csv('jm_cap.csv')
df1.columns

/Users/ugp/anaconda2/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2723: DtypeWarning: Columns (30,35,36,38,55,56) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

Index([u'Unnamed: 0', u'BEGIN_YEARMONTH', u'BEGIN_DAY', u'BEGIN_TIME',
       u'END_YEARMONTH', u'END_DAY', u'END_TIME', u'EPISODE_ID', u'EVENT_ID',
       u'STATE', u'STATE_FIPS', u'YEAR', u'MONTH_NAME', u'EVENT_TYPE',
       u'CZ_TYPE', u'CZ_FIPS', u'CZ_NAME', u'WFO', u'BEGIN_DATE_TIME',
       u'CZ_TIMEZONE', u'END_DATE_TIME', u'INJURIES_DIRECT',
       u'INJURIES_INDIRECT', u'DEATHS_DIRECT', u'DEATHS_INDIRECT',
       u'DAMAGE_PROPERTY', u'DAMAGE_CROPS', u'SOURCE', u'MAGNITUDE',
       u'MAGNITUDE_TYPE', u'FLOOD_CAUSE', u'CATEGORY', u'TOR_F_SCALE',
       u'TOR_LENGTH', u'TOR_WIDTH', u'TOR_OTHER_WFO', u'TOR_OTHER_CZ_STATE',
       u'TOR_OTHER_CZ_FIPS', u'TOR_OTHER_CZ_NAME', u'BEGIN_RANGE',
       u'BEGIN_AZIMUTH', u'BEGIN_LOCATION', u'END_RANGE', u'END_AZIMUTH',
       u'END_LOCATION', u'BEGIN_LAT', u'BEGIN_LON', u'END_LAT', u'END_LON',
       u'EPISODE_NARRATIVE', u'EVENT_NARRATIVE', u'LAST_MOD_DATE',
       u'LAST_MOD_TIME', u'LAST_CERT_DATE', u'LAST_CERT_TIME', u'LAST_MOD',
       u'LAST_CERT', u'ADDCORR_FLG', u'ADDCORR_DATE'],
      dtype='object')

In [39]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 654313 entries, 0 to 654312
Data columns (total 59 columns):
Unnamed: 0            654313 non-null int64
BEGIN_YEARMONTH       654313 non-null int64
BEGIN_DAY             654313 non-null int64
BEGIN_TIME            654313 non-null int64
END_YEARMONTH         654313 non-null int64
END_DAY               654313 non-null int64
END_TIME              654313 non-null int64
EPISODE_ID            654313 non-null int64
EVENT_ID              654313 non-null int64
STATE                 654312 non-null object
STATE_FIPS            654312 non-null float64
YEAR                  654313 non-null int64
MONTH_NAME            654313 non-null object
EVENT_TYPE            654313 non-null object
CZ_TYPE               654313 non-null object
CZ_FIPS               654313 non-null int64
CZ_NAME               654313 non-null object
WFO                   654313 non-null object
BEGIN_DATE_TIME       654313 non-null object
CZ_TIMEZONE           654313 non-null object
END_DATE_TIME         654313 non-null object
INJURIES_DIRECT       654313 non-null int64
INJURIES_INDIRECT     654313 non-null int64
DEATHS_DIRECT         654313 non-null int64
DEATHS_INDIRECT       654313 non-null int64
DAMAGE_PROPERTY       441929 non-null object
DAMAGE_CROPS          395776 non-null object
SOURCE                654313 non-null object
MAGNITUDE             366213 non-null float64
MAGNITUDE_TYPE        213419 non-null object
FLOOD_CAUSE           41277 non-null object
CATEGORY              174 non-null float64
TOR_F_SCALE           15864 non-null object
TOR_LENGTH            15864 non-null float64
TOR_WIDTH             15864 non-null float64
TOR_OTHER_WFO         1309 non-null object
TOR_OTHER_CZ_STATE    1309 non-null object
TOR_OTHER_CZ_FIPS     1309 non-null float64
TOR_OTHER_CZ_NAME     1309 non-null object
BEGIN_RANGE           339451 non-null float64
BEGIN_AZIMUTH         339451 non-null object
BEGIN_LOCATION        422545 non-null object
END_RANGE             122754 non-null float64
END_AZIMUTH           122754 non-null object
END_LOCATION          205779 non-null object
BEGIN_LAT             400305 non-null float64
BEGIN_LON             400306 non-null float64
END_LAT               183537 non-null float64
END_LON               183538 non-null float64
EPISODE_NARRATIVE     545882 non-null object
EVENT_NARRATIVE       379088 non-null object
LAST_MOD_DATE         446377 non-null float64
LAST_MOD_TIME         446377 non-null float64
LAST_CERT_DATE        446377 non-null float64
LAST_CERT_TIME        446377 non-null float64
LAST_MOD              304342 non-null object
LAST_CERT             446377 non-null object
ADDCORR_FLG           37840 non-null float64
ADDCORR_DATE          37840 non-null float64
dtypes: float64(18), int64(15), object(26)
memory usage: 294.5+ MB

In [48]:
df1.DAMAGE_CROPS.describe()

count     395776
unique       759
top        0.00K
freq      366624
Name: DAMAGE_CROPS, dtype: object

In [ ]:
df.head()

In [49]:
df1

,Unnamed: 0,BEGIN_YEARMONTH,BEGIN_DAY,BEGIN_TIME,END_YEARMONTH,END_DAY,END_TIME,EPISODE_ID,EVENT_ID,STATE,...,EPISODE_NARRATIVE,EVENT_NARRATIVE,LAST_MOD_DATE,LAST_MOD_TIME,LAST_CERT_DATE,LAST_CERT_TIME,LAST_MOD,LAST_CERT,ADDCORR_FLG,ADDCORR_DATE
0,0,200301,1,0,200301,31,2359,146513,5338259,COLORADO,...,January consisted of below normal precipitatio...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,200301,1,0,200301,31,2359,147987,5344607,TEXAS,...,NaN,Soil moisture values remain above normal. How...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,200301,1,0,200301,31,2359,147987,5344606,TEXAS,...,NaN,Soil moisture values remain above normal. How...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,200301,1,0,200301,31,2359,147987,5344605,TEXAS,...,NaN,Soil moisture values remain above normal. How...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,200301,1,0,200301,31,2359,147987,5344604,TEXAS,...,NaN,Soil moisture values remain above normal. How...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5,200301,1,0,200301,31,2359,147987,5344603,TEXAS,...,NaN,Soil moisture values remain above normal. How...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,6,200301,1,0,200301,31,2359,147987,5344602,TEXAS,...,NaN,Soil moisture values remain above normal. How...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,7,200301,1,0,200301,31,2359,147987,5344601,TEXAS,...,NaN,Soil moisture values remain above normal. How...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,8,200301,1,0,200301,31,2359,147987,5344600,TEXAS,...,NaN,Soil moisture values remain above normal. How...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,9,200301,1,0,200301,31,2359,146985,5341868,CALIFORNIA,...,Rainfall for the month of January was much bel...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,10,200301,1,0,200301,31,2359,146985,5341867,CALIFORNIA,...,Rainfall for the month of January was much bel...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,11,200301,1,0,200301,31,2359,146985,5341866,CALIFORNIA,...,Rainfall for the month of January was much bel...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,12,200301,1,0,200301,31,2359,146968,5340627,NEW MEXICO,...,A warm and unusually dry month was noted acros...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,13,200301,1,0,200301,31,2359,146968,5340626,NEW MEXICO,...,A warm and unusually dry month was noted acros...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,14,200301,1,0,200301,31,2359,146968,5340625,NEW MEXICO,...,A warm and unusually dry month was noted acros...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,15,200301,1,0,200301,28,2359,146544,5339703,GEORGIA,...,"A large Polar vortex, anchored over the Hudson...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,16,200301,1,0,200301,28,2359,146544,5339695,GEORGIA,...,"A large Polar vortex, anchored over the Hudson...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,17,200301,1,0,200301,28,2359,146544,5339694,GEORGIA,...,"A large Polar vortex, anchored over the Hudson...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,18,200301,1,0,200301,28,2359,146544,5339687,GEORGIA,...,"A large Polar vortex, anchored over the Hudson...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,19,200301,1,0,200301,31,2359,146968,5340618,NEW MEXICO,...,A warm and unusually dry month was noted acros...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,20,200301,1,0,200301,31,2359,146968,5340617,NEW MEXICO,...,A warm and unusually dry month was noted acros...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,21,200301,1,0,200301,31,2359,146968,5340616,NEW MEXICO,...,A warm and unusually dry month was noted acros...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,22,200301,1,0,200301,31,2359,146968,5340636,NEW MEXICO,...,A warm and unusually dry month was noted acros...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,23,200301,1,0,200301,31,2359,146968,5340628,NEW MEXICO,...,A warm and unusually dry month was noted acros...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,24,200301,1,0,200301,31,2359,146968,5340635,NEW MEXICO,...,A warm and unusually dry month was noted acros...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,25,200301,1,0,200301,31,2359,146968,5340634,NEW MEXICO,...,A warm and unusually dry month was noted acros...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,26,200301,1,0,200301,31,2359,146968,5340637,NEW MEXICO,...,A warm and unusually dry month was noted acros...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,27,200301,1,0,200301,31,2359,146968,5340619,NEW MEXICO,...,A warm and unusually dry month was noted acros...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,28,200301,1,0,200301,31,2359,146968,5340633,NEW MEXICO,...,A warm and unusually dry month was noted acros...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,29,200301,1,0,200301,31,2359,146968,5340632,NEW MEXICO,...,A warm and unusually dry month was noted acros...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
654283,51902,201310,31,2140,201310,31,2140,80210,480985,INDIANA,...,Severe weather occurred on October 31st across...,Small tree limbs were downed on personal prope...,20131231.0,1131.0,20131231.0,1416.0,12/31/2013 11:31:14,12/31/2013 14:16:41,NaN,NaN
654284,51903,201310,31,2038,201310,31,2038,80210,480987,INDIANA,...,Severe weather occurred on October 31st across...,A tree was downed through a roof near Thompson...,20131231.0,1131.0,20131231.0,1416.0,12/31/2013 11:31:14,12/31/2013 14:16:41,NaN,NaN
654285,51904,201310,31,2038,201310,31,2038,80210,480988,INDIANA,...,Severe weather occurred on October 31st across...,An official thunderstorm wind gust of 50 mph w...,20131231.0,1131.0,20131231.0,1416.0,12/31/2013 11:31:14,12/31/2013 14:16:41,NaN,NaN
654286,51905,201310,31,2055,201310,31,2100,80201,480253,TENNESSEE,...,A cold front approached the Mid-South during t...,Straight line winds knocked down a few trees j...,99999999.0,9999.0,20131231.0,1125.0,NaN,12/31/2013 11:25:04,NaN,NaN
654287,51906,201310,31,2005,201310,31,2015,80201,480252,TENNESSEE,...,A cold front approached the Mid-South during t...,Straight line winds knocked down trees and pow...,99999999.0,9999.0,20131231.0,1125.0,NaN,12/31/2013 11:25:04,NaN,NaN
654288,51907,201310,31,946,201310,31,950,79484,476809,TENNESSEE,...,A strong cold front triggered high non-thunder...,A gust of 60 mph was recorded at the observati...,20131204.0,2010.0,20131204.0,2123.0,12/04/2013 20:10:27,12/04/2013 21:23:55,NaN,NaN
654289,51908,201310,31,1030,201310,31,1035,79484,476937,TENNESSEE,...,A strong cold front triggered high non-thunder...,A gust of 78 mph was recorded at the observati...,20131204.0,2010.0,20131204.0,2123.0,12/04/2013 20:10:27,12/04/2013 21:23:55,NaN,NaN
654290,51909,201310,31,630,201310,31,900,80224,480894,TEXAS,...,A slow moving storm system and associated fron...,Flooded roads were reported across western Pol...,20131223.0,1227.0,20131223.0,1252.0,12/23/2013 12:27:29,12/23/2013 12:52:47,NaN,NaN
654291,51910,201310,31,1050,201310,31,1330,80224,480899,TEXAS,...,A slow moving storm system and associated fron...,Heavy rain caused road closures due to floodin...,20131223.0,1247.0,20131223.0,1252.0,12/23/2013 12:47:21,12/23/2013 12:52:47,NaN,NaN
654292,51911,201310,31,1105,201310,31,1235,80224,480895,TEXAS,...,A slow moving storm system and associated fron...,There were road clousures due to flooding in a...,20131223.0,1248.0,20131223.0,1252.0,12/23/2013 12:48:22,12/23/2013 12:52:47,NaN,NaN
654293,51912,201310,31,2041,201310,31,2041,80210,481793,INDIANA,...,Severe weather occurred on October 31st across...,"A thunderstorm wind gust, estimated at 65 mph,...",20131231.0,1131.0,20131231.0,1416.0,12/31/2013 11:31:14,12/31/2013 14:16:41,NaN,NaN
654294,51913,201310,31,2044,201310,31,2044,80210,481794,INDIANA,...,Severe weather occurred on October 31st across...,"A thunderstorm wind gust, estimated at 70 mph,...",20131231.0,1131.0,20131231.0,1416.0,12/31/2013 11:31:14,12/31/2013 14:16:41,NaN,NaN
654295,51914,201310,31,2054,201310,31,2054,80210,481795,INDIANA,...,Severe weather occurred on October 31st across...,"A thunderstorm wind gust, measured at 62 mph, ...",20131231.0,1131.0,20131231.0,1416.0,12/31/2013 11:31:14,12/31/2013 14:16:41,NaN,NaN
654296,51915,201310,31,2103,201310,31,2103,80210,481796,INDIANA,...,Severe weather occurred on October 31st across...,A thunderstorm wind gust was measured on North...,20131231.0,1131.0,20131231.0,1416.0,12/31/2013 11:31:14,12/31/2013 14:16:41,NaN,NaN
654297,51916,201310,31,2103,201310,31,2103,80210,481797,INDIANA,...,Severe weather occurred on October 31st across...,"A thunderstorm wind gust, estimated at 60 mph,...",20131231.0,1131.0,20131231.0,1416.0,12/31/2013 11:31:14,12/31/2013 14:16:41,NaN,NaN
654298,51917,201310,31,2105,201310,31,2105,80210,481798,INDIANA,...,Severe weather occurred on October 31st across...,"A thunderstorm wind gust, measured at 65 mph, ...",20131231.0,1131.0,20131231.0,1416.0,12/31/2013 11:31:14,12/31/2013 14:16:41,NaN,NaN
654299,51918,201310,31,600,201310,31,835,80243,480551,MARYLAND,...,A tropical air mass moved into the Mid Atlanti...,Visibilities of a quarter mile or less were me...,99999999.0,9999.0,20131222.0,807.0,NaN,12/22/2013 08:07:27,NaN,NaN
654300,51919,201310,31,1820,201310,31,1822,79553,477100,ILLINOIS,...,An outbreak of severe thunderstorms and isolat...,The tornado passed through East Cape Girardeau...,20131202.0,1951.0,20131219.0,1119.0,12/02/2013 19:51:25,12/19/2013 11:19:50,NaN,NaN
654301,51920,201310,31,1851,201310,31,1859,79553,477105,ILLINOIS,...,An outbreak of severe thunderstorms and isolat...,This tornado contained estimated peak winds ne...,20131202.0,1951.0,20131219.0,1119.0,12/02/2013 19:51:25,12/19/2013 11:19:50,NaN,NaN
654302,51921,201310,31,1859,201310,31,1904,79553,477106,ILLINOIS,...,An outbreak of severe thunderstorms and isolat...,"This tornado, which began in Williamson County...",20131202.0,1951.0,20131219.0,1119.0,12/02/2013 19:51:25,12/19/2013 11:19:50,NaN,NaN
654303,51922,201310,31,630,201310,31,1045,79364,476104,LOUISIANA,...,A deep upper level trough moved out of the Int...,Allen-Marthaville Road was covered in 1-2 feet...,20131210.0,2055.0,20131220.0,1708.0,12/10/2013 20:55:26,12/20/2013 17:08:59,NaN,NaN
654304,51923,201310,31,1637,201310,31,1637,79918,480425,PUERTO RICO,...,An upper level trough produced unstable atmosp...,Pea size hail was reported over Puerto Real se...,20131217.0,1448.0,20140102.0,929.0,12/17/2013 14:48:43,01/02/2014 09:29:52,NaN,NaN
654305,51924,201310,31,300,201310,31,430,80179,481084,TEXAS,...,Significant flooding occurred in the south and...,Heavy rain and flash flooding led to the closu...,20131226.0,1500.0,20131230.0,845.0,12/26/2013 15:00:23,12/30/2013 08:45:34,NaN,NaN
654306,51925,201310,31,630,201310,31,630,79593,481048,TEXAS,...,Prolonged flow from the Gulf of Mexico produce...,Thunderstorms produced heavy rain that led to ...,20131226.0,2015.0,20131227.0,49.0,12/26/2013 20:15:51,12/27/2013 00:49:39,NaN,NaN
654307,51926,201310,31,2120,201310,31,2120,80210,481799,INDIANA,...,Severe weather occurred on October 31st across...,"A thunderstorm wind gust, estimated at 75 mph,...",20131231.0,1131.0,20131231.0,1416.0,12/31/2013 11:31:14,12/31/2013 14:16:41,NaN,NaN
654308,51927,201310,31,2042,201310,31,2042,80210,481800,INDIANA,...,Severe weather occurred on October 31st across...,Trees were reported down at Eller and 106th St...,20131231.0,1131.0,20131231.0,1416.0,12/31/2013 11:31:14,12/31/2013 14:16:41,NaN,NaN
654309,51928,201310,31,2045,201310,31,2045,80210,481801,INDIANA,...,Severe weather occurred on October 31st across...,"A 20-inch diameter, living tree was broke off ...",20131231.0,1131.0,20131231.0,1416.0,12/31/2013 11:31:14,12/31/2013 14:16:41,NaN,NaN
654310,51929,201310,31,2045,201310,31,2045,80210,481802,INDIANA,...,Severe weather occurred on October 31st across...,Trees were reported to be downed on a vehicle ...,20131231.0,1131.0,20131231.0,1416.0,12/31/2013 11:31:14,12/31/2013 14:16:41,NaN,NaN
654311,51930,201310,31,2047,201310,31,2047,80210,481803,INDIANA,...,Severe weather occurred on October 31st across...,Patio furniture was damaged at a residence in ...,20131231.0,1131.0,20131231.0,1416.0,12/31/2013 11:31:14,12/31/2013 14:16:41,NaN,NaN
654312,51931,201310,31,2049,201310,31,2049,80210,481804,INDIANA,...,Severe weather occurred on October 31st across...,Some tops of trees were snapped and a 30-inch ...,20131231.0,1131.0,20131231.0,1416.0,12/31/2013 11:31:14,12/31/2013 14:16:41,NaN,NaN